version: '3.8'

services:
  app:
    build: .
    container_name: message_board_app2
    ports:
      - "${PROJECT_PORT}:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/message_board?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  db:
    image: mysql:8.0
    container_name: message_board_mysql2    # 移除了 ¥ 符号
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: message_board
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
